name: build

on:
  push:
    branches:
      - '**'
      # - 'main'
      # - 'release/*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/turbo

      - name: Build
        run: pnpm build --cache-dir=.turbo --filter @siemens/ix

  documentation:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/turbo

      - name: Documentation
        run: pnpm build --cache-dir=.turbo --filter documentation
