name: build

on:
  push:
    branches:
      - '**'
      # - 'main'
      # - 'release/*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/turbo

      - name: Build
        run: pnpm build --cache-dir=.turbo --filter \!documentation

  # documentation:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - uses: ./.github/workflows/actions/turbo

  #     - name: Documentation
  #       run: pnpm build --cache-dir=.turbo --filter documentation

  visual-test:
    needs: [build]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.32.1-focal
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/turbo

      - name: Install Playwright Browsers
        run: yarn playwright install chromium

      - name: Visual Regression
        run: pnpm visual-regression --cache-dir=.turbo

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            ./packages/core/playwright-report/
            ./packages/aggrid/playwright-report/
          retention-days: 2
